/**
 * check-attribution.ts — proves no AI tool is credited anywhere in this repo.
 *
 * Two surfaces, because either one alone is a gap:
 *   1. the working tree — a trailer or stamp inside a tracked file
 *   2. the full history — every commit message on every ref
 *
 * What this deliberately does NOT hunt: the words "claude", "openai",
 * "anthropic", "AI". Those name the provider this product classifies failures
 * with. They are the product, not an attribution, and a gate that flagged them
 * would push a maintainer towards deleting the feature to satisfy the scanner.
 *
 * Exit codes: 0 clean, 1 violation found, 2 the check could not run.
 */
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { extname } from "node:path";

const ROOT = process.cwd();

/** Attribution markers. Vendor product names are deliberately absent. */
const TREE_PATTERNS: ReadonlyArray<{ name: string; re: RegExp }> = [
  { name: "co-author trailer", re: /^\s*co-authored-by:/gim },
  {
    name: "generated-with stamp",
    re: /generated\s+(with|by)\s+\[?(codebuff|claude|cursor|copilot|chatgpt|aider|devin|copilot)/gi,
  },
  // The robot emoji and the phrase "AI-generated" are attribution markers only
  // where they APPEAR AS A STAMP - a file header, a banner on its own line, a
  // commit trailer. The same characters inside product source are a product
  // decision: this project's own pipeline diagram labels its classifier node
  // with a robot, and hiding that would misrepresent what the software does.
  //
  // Both are anchored to line starts and to attribution shapes ("generated by",
  // "written by") rather than the bare words. A guard that fires on legitimate
  // content is a guard that gets switched off.
  { name: "robot emoji as a stamp", re: /^\s*(?:\*\*)?\u{1F916}.*$/gmu },
  { name: "AI-generated banner", re: /^\s*(?:\/\*\*|\/\*)?\s*(?:ai|llm)[- ]generated\b/gimu },
  {
    name: "written-by-an-AI banner",
    re: /^\s*(?:\/\*\*|\/\*)?\s*(?:written|authored|created|produced)\s+by\s+(?:an?\s+)?(?:ai|llm|chatgpt|claude|codex|copilot)\b/gimu,
  },
  { name: "agent co-author", re: /^\s*co-authored-by:.*(bot|agent|assistant|codex|copilot)/gim },
];

const COMMIT_PATTERNS: ReadonlyArray<{ name: string; re: RegExp }> = [
  { name: "co-author trailer", re: /^\s*co-authored-by:/gim },
  {
    name: "generated-with stamp",
    re: /generated\s+(with|by)\s+\[?(codebuff|claude|cursor|copilot|chatgpt|aider|devin)/gi,
  },
  { name: "robot emoji", re: /\u{1F916}/gu },
  { name: "AI-generated banner", re: /(ai|llm)[- ]generated\b/gi },
];

/** Files a scanner must not read, or it will always find its own patterns. */
const SELF = new Set([
  "scripts/check-attribution.ts",
  "docs/decisions/0006-no-attribution-without-exception.md",
]);

const SCANNABLE = new Set([
  ".ts",
  ".tsx",
  ".js",
  ".mjs",
  ".cjs",
  ".json",
  ".md",
  ".mdx",
  ".yml",
  ".yaml",
  ".txt",
  ".sh",
  ".css",
  ".html",
]);

function git(args: string[]): string {
  return execFileSync("git", args, { cwd: ROOT, encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
}

function trackedFiles(): string[] {
  try {
    return git(["ls-files"]).split("\n").filter(Boolean);
  } catch {
    console.error("check-attribution: not a git repository (or git unavailable)");
    process.exit(2);
  }
}

function scanTree(files: string[]): string[] {
  const findings: string[] = [];
  for (const file of files) {
    if (SELF.has(file)) continue;
    if (!SCANNABLE.has(extname(file))) continue;
    let text: string;
    try {
      text = readFileSync(`${ROOT}/${file}`, "utf8");
    } catch {
      continue;
    }
    for (const { name, re } of TREE_PATTERNS) {
      re.lastIndex = 0;
      const match = re.exec(text);
      if (match) {
        const line = text.slice(0, match.index).split("\n").length;
        findings.push(`${file}:${line} — ${name}`);
      }
    }
  }
  return findings;
}

function scanHistory(): string[] {
  const findings: string[] = [];
  let subjects: string;
  try {
    subjects = git(["log", "--all", "--format=%H%x1f%B%x1e"]);
  } catch {
    console.error("check-attribution: could not read git history");
    process.exit(2);
  }
  for (const record of subjects.split("\u001e")) {
    const trimmed = record.trim();
    if (!trimmed) continue;
    const [sha = "", body = ""] = trimmed.split("\u001f");
    if (!sha) continue;
    for (const { name, re } of COMMIT_PATTERNS) {
      re.lastIndex = 0;
      if (re.test(body)) {
        findings.push(`commit ${sha.slice(0, 8)} — ${name}`);
      }
    }
  }
  return findings;
}

function main(): void {
  const files = trackedFiles();
  const treeFindings = scanTree(files);
  const historyFindings = scanHistory();

  const identity = git(["log", "--format=%an <%ae>"]).trim().split("\n").filter(Boolean);
  const authors = new Set(identity.map((line) => line.split(" <")[0]));

  console.log(`check-attribution: ${files.length} tracked file(s) scanned`);
  console.log(
    `check-attribution: ${historyFindings.length === 0 ? "all commit messages scanned" : "commit messages scanned"}`,
  );
  console.log(`check-attribution: distinct author name(s) in history: ${authors.size}`);

  const findings = [...treeFindings, ...historyFindings];

  if (authors.size > 1) {
    findings.push(
      `history carries ${authors.size} distinct author name(s): ${[...authors].join(", ")}`,
    );
  }

  if (findings.length > 0) {
    console.error("\nATTRIBUTION VIOLATIONS:");
    for (const finding of findings) console.error(`  - ${finding}`);
    process.exit(1);
  }

  console.log("\nATTRIBUTION PASS — no AI tool credited in files, history or authorship.");
  process.exit(0);
}

main();
